resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6 #Tamaño de la ventana deslizante para el circuit breaker
        failure-rate-threshold: 50 #Umbral de tasa de fallos para abrir el circuito
        wait-duration-in-open-state: 20s # Duracion de espera en estado abierto antes de intentar recuperar
        permitted-number-of-calls-in-half-open-state: 4 # Numero permitido de llamadas en estado medio abierto
        slow-call-rate-threshold: 50 #Umbral de tasa de llamadas lentas para activar el circuito
        slow-call-duration-threshold: 2s
    instances:
      productos:
        base-config: defecto #Configuracion base para la instancia 'productos'  del circuit braker
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s # Duracion de tiempo limite para la instancia 'productos'
    instances:
      productos:
        base-config: defecto # Configuracion base para el limite de tiempo de la instancia 'productos'

spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
          - Path=/api/productos/**
        filters:
          - name: CircuitBreaker
            args:
              name: productos
              statusCodes: 500
              fallbackUri: forward:/api/items/ver/9/cantidad/5
          - StripPrefix=2 #Elimina los dos primeros segmentos del path de la solicitud
          - EjemploCookie=Hola chicos como estan, usuario, PabloAyala # Ejemplo de filtro personalizado para manejar cookies
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
          - AddRequestHeader=token-request, 123456 #Agrega el encabezado 'token-request' con el valor '123456' a la solicitud
          - AddResponseHeader=token-response, 12345678 # Agrega el encabezado 'token-response' con el valor '12345678' a la respuesta
          - SetResponseHeader=Content-Type, text/plain # Establece el encabezado 'Content-Type' de la respuesta como 'text/plain'
          - AddRequestParameter=nombre, pablo # Agrega el parametro de consulta 'nombre=pablo' a la solicitud
