# Configuración del circuit breaker usando Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6 # Tamaño de la ventana deslizante para contabilizar los fallos
        failure-rate-threshold: 50 # Umbral de tasa de fallos para abrir el circuit breaker (en porcentaje)
        wait-duration-in-open-state: 20s # Tiempo de espera en estado abierto antes de intentar recuperarse
        permitted-number-of-calls-in-half-open-state: 4  # Número de llamadas permitidas en estado semi-abierto
        slow-call-rate-threshold: 50  # Umbral de tasa de llamadas lentas para considerarlas como fallos
        slow-call-duration-threshold: 2s # Umbral de duración para considerar una llamada como lenta
    instances:
      items:
        base-config: defecto # Configuración base para la instancia del circuit breaker "items"
        # Configuración del time limiter usando Resilience4j
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s  # Duración máxima permitida para una operación antes de agotar el tiempo
    instances:
      items:
        base-config: defecto # Configuración base para la instancia del time limiter "items"
